name: Release
on:
  push:
    branches: [ release ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_API_SECRET }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Get Current Version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: "pyproject.toml"
          field: project.version
        id: get_current_version

      - name: Build Python Package
        run: rm -rf build *.egg-info/ && python3 -m build

      - name: Create Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: "${{steps.get_current_version.outputs.value}}"
          github_token: ${{ secrets.GH_API_SECRET }}

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_SECRET }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v${{steps.get_current_version.outputs.value}}'
          body: ${{steps.build_changelog.outputs.changelog}}
          token: ${{ secrets.GH_API_SECRET }}

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # 1.12.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Sync Release with Master
        run: |
          git fetch origin
          git checkout release
          git pull origin release
          git checkout master
          git pull origin master
          git merge release --ff-only
          git push origin master
